/* Install the database tables */

DROP INDEX EVENT_HIST_EVENT_TYPE_IDX;

DROP TRIGGER EVENT_HIST_TIBR;
DROP TRIGGER OBJ_TIBR;
DROP TRIGGER EVENT_DECISION_TIBR;
DROP TRIGGER EVENT_CHOICE_NODE_TIBR;

DROP SEQUENCE EVENT_HIST_SEQ;
DROP SEQUENCE OBJ_SEQ;
DROP SEQUENCE EVENT_DECISION_SEQ;
DROP SEQUENCE EVENT_CHOICE_SEQ;

DROP TABLE EVENT_SCORING;
DROP TABLE EVENT_CHOICE;
DROP TABLE EVENT_DECISION;
DROP TABLE EVENT_HIST;
DROP TABLE OBJ;
DROP TABLE EVENT_CHOICE_NODE;

CREATE TABLE EVENT_HIST
( EVENT_HIST_ID     NUMBER NOT NULL 
, EVENT_DECISION_ID NUMBER NOT NULL 
, EVENT_TYPE        VARCHAR2(10) NOT NULL
, CHOICE_FACING     NUMBER NOT NULL
, CONSTRAINT EVENT_HIST_PK PRIMARY KEY ( EVENT_HIST_ID ) ENABLE );
/

CREATE TABLE EVENT_SCORING
( EVENT_HIST_ID NUMBER NOT NULL 
, CONSTRAINT EVENT_SCORING_FK FOREIGN KEY ( EVENT_HIST_ID ) 
    REFERENCES EVENT_HIST ( EVENT_HIST_ID ) ENABLE );
/

CREATE TABLE EVENT_DECISION
( EVENT_DECISION_ID NUMBER NOT NULL
, OBJ_ID            NUMBER
, EVENT_CHOICE_ID   NUMBER
, CONSTRAINT EVENT_DECISION_PK PRIMARY KEY ( EVENT_DECISION_ID ) ENABLE );
/

CREATE TABLE EVENT_CHOICE
( EVENT_CHOICE_ID NUMBER NOT NULL
, CHOICE_FACING   NUMBER NOT NULL
, CHOICE_TARGET   VARCHAR2(10)
, CHOICE_ORIG_X   NUMBER
, CHOICE_ORIG_Y   NUMBER
, CHOICE_ORIG_Z   NUMBER
, CHOICE_DIR_X    NUMBER
, CHOICE_DIR_Y    NUMBER
, CHOICE_DIR_Z    NUMBER
, CONSTRAINT EVENT_CHOICE_PK PRIMARY KEY ( EVENT_CHOICE_ID, CHOICE_FACING )
, CONSTRAINT EVENT_CHOICE_FK FOREIGN KEY ( EVENT_CHOICE_ID ) 
    REFERENCES EVENT_CHOICE_NODE ( EVENT_CHOICE_ID ) ENABLE );
/

CREATE TABLE OBJ
( OBJ_ID   NUMBER NOT NULL,
  OBJ_CD   NUMBER NOT NULL,
  OBJ_TEAM VARCHAR2(10)
, CONSTRAINT OBJ_PK PRIMARY KEY ( OBJ_ID ) ENABLE );
/

CREATE TABLE EVENT_CHOICE_NODE
( EVENT_CHOICE_ID NUMBER NOT NULL
, CT0             VARCHAR2(10)
, CT1             VARCHAR2(10)
, CT2             VARCHAR2(10)
, CT3             VARCHAR2(10)
, CT4             VARCHAR2(10)
, CT5             VARCHAR2(10)
, CT6             VARCHAR2(10)
, CONSTRAINT EVENT_CHOICE_NODE_PK PRIMARY KEY ( EVENT_CHOICE_ID ));
/

CREATE SEQUENCE EVENT_HIST_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE OBJ_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE EVENT_DECISION_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE EVENT_CHOICE_SEQ INCREMENT BY 1 START WITH 1;
/

CREATE OR REPLACE TRIGGER EVENT_HIST_TIBR 
BEFORE INSERT ON EVENT_HIST 
FOR EACH ROW 
BEGIN
  select EVENT_HIST_SEQ.nextval into :new.EVENT_HIST_ID from dual;
END;
/

CREATE OR REPLACE TRIGGER OBJ_TIBR 
BEFORE INSERT ON Obj 
FOR EACH ROW 
BEGIN
  select OBJ_SEQ.nextval into :new.OBJ_ID from dual;
end;
/

CREATE OR REPLACE TRIGGER EVENT_DECISION_TIBR 
BEFORE INSERT ON EVENT_DECISION 
FOR EACH ROW 
BEGIN
  select EVENT_DECISION_SEQ.nextval into :new.EVENT_DECISION_ID from dual;
END;
/

CREATE OR REPLACE TRIGGER EVENT_CHOICE_NODE_TIBR 
BEFORE INSERT ON EVENT_CHOICE_NODE 
FOR EACH ROW 
BEGIN
  select EVENT_CHOICE_SEQ.nextval into :new.EVENT_CHOICE_ID from dual;
END;
/

CREATE INDEX EVENT_HIST_EVENT_TYPE_IDX ON EVENT_HIST (EVENT_TYPE);
/f